server:
  port: 8888

spring:
  datasource:
    name: UserDb
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8
    username: dbuser
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver