server:
  port: 8888
  servlet:
    session:
      timeout: 10

spring:
  datasource:
    url: jdbc:mysql://192.168.1.25:3306/wxpay-boss?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Yl888888
    driver-class-name: com.mysql.jdbc.Driver